.devcontainer/python-container/devcontainer.json
.vscode/settings.json
Dockerfile
README.md
app/app.py
app/blueprints/fund_builder/routes.py
compose.override.yml
docker-compose.yml
pyproject.toml
tasks/db_tasks.py
tests/test_db.py
tests/test_integration.py

Renaming from self-serve to FAB

BAU renaming to FAB

---

Dockerfile
requirements-dev.in
requirements-dev.txt
requirements.in
requirements.txt

Moved requirements into own file instead of relying on the base image as this work has been parked for a bit.

Removing ref to base image

---

project.toml

FS-4587:Exclude some repositories from built container images

FS-4587:Exclude some repositories from built container images

---

app/blueprints/fund_builder/forms/round.py

FS 409: Update datetime formats for round config

FS 4609: Update datetime formats for round config

---

app/db/queries/application.py
tests/test_clone.py

https://dluhcdigital.atlassian.net/browse/FS-4533
add a test for round clone

add clone round test

---

app/db/migrations/versions/~2024_09_11_0753-846793bff0d3_.py

FS-4616: Fix migration

---

.vscode/settings.json
docker-compose.yml

Couple of small settings changes to make the dev container process smoother
- Adding black formatter interpreter settings to the vscode settings file used in the container to remove errors on startup
- Making the dev container build use requirements-dev.txt

Bau fix dev container settings

---

app/create_app.py
config/envs/default.py
config/envs/development.py
config/envs/unit_test.py

Updated config settings to read `SECRET_KEY` from the environment which should fix bandit errors
_If manual testing is needed, give suggested testing steps_

Changing flask secret key to be read from environment

---

config/envs/default.py
config/envs/dev.py
copilot/fsd-fund-application-builder/addons/fsd-fund-application-builder-cluster.yml
copilot/fsd-fund-application-builder/manifest.yml

db url fix for each env

---

.github/workflows/copilot_deploy.yml

Set build_static_assets to true so the styles work

build static assets

---

config/envs/default.py
config/envs/dev.py
config/envs/development.py
config/envs/unit_test.py
copilot/fsd-fund-application-builder/manifest.yml

Update manifest to reference secret key from aws environment

fix secret key

---

app/blueprints/fund_builder/routes.py
app/blueprints/self_serve/routes.py

Change the index function name after refactoring

Correct index name after refactoring

---

app/blueprints/fund_builder/forms/round.py
app/blueprints/fund_builder/routes.py
app/blueprints/fund_builder/templates/fund.html
app/blueprints/fund_builder/templates/fund_config.html
app/blueprints/fund_builder/templates/round.html
app/create_app.py
app/db/models/fund.py
app/db/models/round.py
app/db/queries/fund.py
app/db/queries/round.py
app/templates/macros/wtfToGovUk.html
tests/conftest.py
tests/helpers.py
tests/test_routes.py

Edit fund and round config: https://dluhcdigital.atlassian.net/browse/FS-4652
- New Routes: Added /fund/<fund_id> and /round/<round_id> routes to enable updating fund and round details via forms.
- Frontend Enhancements: Introduced “Edit” buttons in the fund_config template for easier access to update forms, used fund and round templates to handle create and update.
- JSON Column Mutability: Addressed SQLAlchemy’s default immutability of JSON columns by using MutableDict.as_mutable to ensure changes are tracked and persisted.
- Form and Database Synchronization: Fixed discrepancies between form inputs and database fields, particularly for minute fields.
- Testing Improvements: 
- Created test_routes.py to cover the new routes.
- Developed helpers.py to include utility functions for the …

FS-4652: implement fund and round update features

---

docker-compose-dev.yml

Updating the host names and container names in the dev docker compose file as they were conflicting with the dev container names

bau updating docker compose host names

---

copilot/fsd-fund-application-builder/manifest.yml

FS-4638: Add correct form runner external host variable for form preview
Added correct form runner external host variable for form preview

FS-4638: Add correct form runner external host variable for form preview

---

tests/test_config_export.py
tests/test_config_import.py
tests/test_data/favourite-colours-sarah.json
tests/test_data/optional-all-components.json
tests/test_data/required-all-components.json
tests/test_integration.py

Made some changes to the output file naming for the demo, forgot to update tests 🤦 Now updated.
_If manual testing is needed, give suggested testing steps_

fixing tests after refactoring output files

---

app/blueprints/fund_builder/routes.py
config/__init__.py
config/envs/production.py
config/envs/test.py
copilot/fsd-fund-application-builder/manifest.yml

FS 4730 : FAB uat deployment changes

FS 4730 : FAB uat deployment changes 

---

app/blueprints/fund_builder/forms/templates.py
app/blueprints/templates/routes.py
app/blueprints/templates/templates/edit_form_template.html
app/blueprints/templates/templates/view_templates.html

Added ability to delete a template, and to update the template name, tasklist name and url-path
_If manual testing is needed, give suggested testing steps_

Allow editing of templates

---

.github/workflows/copilot_deploy.yml

Forgot to remove the jobs I commented out from the `needs` list of further jobs

removing commented out jobs from needs

---

app/blueprints/fund_builder/forms/fund.py
app/blueprints/fund_builder/templates/fund.html

For COF EOI we need more than 6 characters in the short name field (as per existing config) so have increased the allowed length.
Also made description a multiline text field as it better fits the data

increasing length of short name and making description a multiline field

---

.devcontainer/devcontainer.json
app/db/models/application_config.py
app/export_config/generate_form.py
app/export_config/generate_fund_round_form_jsons.py
tasks/test_data.py
tests/test_config_export.py
tests/test_generate_form.py

Updated the form json export to use the fund description in the `name` element of the form, not `name_in_apply_json` to be consistent with existing forms
_If manual testing is needed, give suggested testing steps_

fixing title on exported forms

---

app/blueprints/fund_builder/forms/round.py
app/blueprints/fund_builder/routes.py
app/blueprints/fund_builder/templates/round.html

Added welsh fields to round config screen and associated routes.
Add or edit a round and see the new fields

adding welsh to round

---

.github/workflows/copilot_deploy.yml

Updating the run name to not include Prod as it doesn't go to prod

Updating run name

---

app/blueprints/fund_builder/forms/round.py
app/blueprints/fund_builder/routes.py
app/export_config/generate_fund_round_config.py
app/export_config/helpers.py
app/shared/data_classes.py
tests/test_config_export.py

FS-4775: Fix export ggis_scheme_reference_number field for fund_config

FS-4775 : Fix export ggis field

---

.idea/runConfigurations/FAB.xml
app/blueprints/fund_builder/routes.py
app/export_config/generate_form.py
app/export_config/generate_fund_round_config.py
app/export_config/generate_fund_round_form_jsons.py
app/export_config/generate_fund_round_html.py
app/export_config/helpers.py
tests/test_config_export.py

https://mhclgdigital.atlassian.net/browse/FS-4863
https://mhclgdigital.atlassian.net/browse/FS-4862
when downloading the configs, create a unique folder and zip file to download and then delete those from the given directory, and this will save space and uniqueness will guarantee the configuration correctness and will not replace with each other
adding IntelliJ IDEA configuration and this will allow other developers to start application locally 
updating source_path if the condition since some of them not having the source_path in the condition 

FS-4863/FS-4862: fix download issue and some few bug fixes 

---

app/blueprints/fund_builder/routes.py
app/blueprints/fund_builder/templates/round.html

Fix added to select  same fund if an error is thrown on round creation.
- [x ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")

FS-4866 : fix fund dropdown in round creation

---

app/blueprints/fund_builder/routes.py
app/export_config/generate_assessment_config.py
app/export_config/generate_fund_round_config.py
app/export_config/helpers.py
tasks/__init__.py
tasks/export_tasks.py
tests/test_config_export.py

https://mhclgdigital.atlassian.net/browse/FS-4812
In this PR we have covered minimal assessment configuration changes and this will not do any scored or unscored criteria check instead it will just generate fields that can be leverage for manual configuration of assessment 
`
{
"fund_round_to_assessment_mapping": {
"schema_id": "COF25R1_assessment",
"unscored_sections": [
{
"id": "about-your-organisation",
"name": "About your organisation",
"sub_criteria": [
{
"id": "organisation-information-cof-25",
"name": "Organisation Information",
"themes": [
{
"id": "organisation-names",
"name": "Organisation names",
"answers": [
{
"field_id": "WWWWxy",
"form_name": "organisation-information-cof-25",
"field_type": "textField",
"presentation_type": "text",
"question": "Your expression of interest …

FS-4812: minimal assessment configuration changes

---

app/blueprints/fund_builder/forms/round.py

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4873**
Renaming Contact fields 
- Contact Email -> Fund team email address
- Contact Phone -> Fund team phone number
- Contact Textphone -> Fund team text phone number

FS-4873: Contact field name changes

---

copilot/fsd-fund-application-builder/manifest.yml

It doesn't look like FAB relies on the account store. Clarify this and remove old references so if its needed new references point to the right place.

FSPT-190 Clarify that the account store isn't used

---

app/blueprints/fund_builder/routes.py
app/shared/helpers.py

[Add an error banner to notify users when there are issues with mandatory fields (Add a Round)](https://mhclgdigital.atlassian.net/browse/FS-4848)
Add field names to error messages in error message banner.

FS-4848 - Add field names to error messages in error message banner

---

app/import_config/load_form_json.py
tests/test_config_import.py
tests/test_integration.py

FS:4888: Fix url path for template.

FS-4888: fix template url path

---

app/blueprints/index/templates/dashboard.html
tests/blueprints/index/test_routes.py

https://mhclgdigital.atlassian.net/browse/FS-4926
Updating FAB Home page as per Mika's new design here: https://www.figma.com/design/H2YCtJp5KfYpqZLP34vWyg/FAB-(Fund-Application-Builder)?node-id=3915-25588&t=k8COZjVbmqcsfHyr-0

FS-4926 - Updating Home page to match Mika's new UI design

---

app/templates/footer.html

**Ticket : https://mhclgdigital.atlassian.net/browse/FS-4951**
Adding minimal gov footer as figma requested 
Go to every page and it should be visible in the bottom

Adding a gov footer component

---

app/blueprints/fund/routes.py

We need to pass current page to GenericTablePage in the view_all_funds route in order for pagination to work.

Bugfix - Fixes grants table pagination

---

app/create_app.py
config/envs/default.py
config/envs/development.py
pyproject.toml
uv.lock

This should help with local development, by making it easier to eg identify what SQL queries are run, see log messages, see rendered templates etc.
* Re-build the `fab` docker compose service
* Run it
* Go through some of the FAB pages - open the toolbar on the right and you should be able to see SQL queries, etc.

Add and instrument flask-debugtoolbar

---

app/blueprints/template/routes.py
app/blueprints/template/services.py
app/blueprints/template/templates/partials/view_template_page_description.html
app/blueprints/template/templates/partials/view_templates_details_description.html
app/blueprints/template/templates/view_templates.html
app/shared/generic_table_page.py
app/templates/macros/genericTablePage.html
config/envs/default.py
copilot/fsd-fund-application-builder/manifest.yml
tests/blueprints/template/test_routes.py

**Ticket : https://mhclgdigital.atlassian.net/browse/FS-4931**
In this PR focus is to update the generic table page to have few features 
1. Adding a link under the description 
2. Detail should get a html description since templates page having a longer description and it should be added as a html 
1. Go to template page should see new components 
2. other pages should work Grants, Applications

FS-4931 Template page changes

---

app/blueprints/fund/routes.py
app/blueprints/round/routes.py
app/shared/helpers.py
app/templates/partials/flash_template.html

adding flash message as a template
Grant creation & Application creation will give the template

flash loading with html template

---

app/blueprints/fund/forms.py
app/blueprints/fund/templates/fund_details.html
app/blueprints/round/forms.py
app/blueprints/round/routes.py
app/blueprints/round/services.py
app/blueprints/round/templates/round_details.html
app/db/queries/clone.py
tests/blueprints/fund/test_routes.py
tests/blueprints/round/test_routes.py

Ticket : https://mhclgdigital.atlassian.net/browse/FS-4936
1. Click on an Application name in list of applications page (ex: https://fund-application-builder.levellingup.gov.localhost:3011/rounds/)
2. Should render the screen with application details
3. Application fields can be edited by clicking on Change link against the field, redirecting to update Round(application) page. Clicking save and continue should redirect back to application details
4. Clicking on "Copy application" should clone the round to a new round with title having …

FS-4936: Add application details API and template

---

app/blueprints/index/templates/dashboard.html
app/templates/base.html
app/templates/navigation.html

Updates homepage content to match the frozen designs, with a couple of small tweaks to bring the page layout closer to the designs.
Include a small commit which makes 'Fund application builder' service name title case in the header and navigation, as per designs.

FS-4975: Update homepage content

---

app/templates/select_application.html
app/templates/select_fund.html

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4982**
accessibility fixes for the grants and application selection screens
Use axe dev tools and if you see 0 then bugs are gone

FS-4982: accessibility fixes for the grants and application selection screens

---

app/blueprints/fund/forms.py
app/blueprints/fund/routes.py
app/blueprints/fund/templates/fund.html
app/blueprints/fund/templates/fund_details.html
app/blueprints/fund/templates/view_all_funds.html
app/blueprints/round/templates/round_details.html
app/db/models/fund.py
app/templates/partials/flash_template.html
app/templates/select_fund.html
tests/blueprints/fund/test_routes.py

Ticket: https://mhclgdigital.atlassian.net/browse/FS-4969
Update Add Edit grant flows
Add a Grant
1. Changes Added to update Add a new grant and Update Grant templates use wtf forms
2. Click on Add a new grant from home/dashboard. Add details and click on continue and save. should redirect to create application/round page
3. Click on Add a new grant from select grant page. Add details and click on continue and save. should redirect to create application/round page
4. Click on Add a new grant from grants/funds list . Add details and …

FS-4969 :Add and Edit grant template update with navigation

---

app/blueprints/round/routes.py

changing the selection to have grant name instead of application name
Go to the grant selection screen now grant name should be there

bau: changing the selection to have grant name instead of application name

---

app/blueprints/round/templates/round_details.html

Ticket : https://mhclgdigital.atlassian.net/browse/FS-4994)
1. From Application details of a an aApplication, Click on change application heading under Application tile, Should redirect to Grant edit page.
2.

FS-4994: Bugfix Add missing round id for update grant from application details

---

app/blueprints/round/services.py

application table minor fix column grant should get the grant name instead of the title

bau : application table minor fix

---

app/blueprints/application/forms.py
app/blueprints/application/templates/view_questions.html
app/blueprints/fund/forms.py
app/blueprints/fund/routes.py
app/blueprints/fund/templates/fund_details.html
app/blueprints/round/forms.py
app/blueprints/round/templates/round.html
app/blueprints/round/templates/round_details.html
app/blueprints/template/templates/template.html
app/blueprints/template/templates/template_details.html
app/shared/forms.py
app/templates/select_application.html
tests/blueprints/fund/test_routes.py
tests/blueprints/template/test_routes.py

A few content changes across FAB following content review with Chanel and my own scooting around the app to spot discrepancies between the current app and the Figma designs.
Also includes updates to all the visuallyHiddenText to be descriptive and match the field names, as per FS-4971.

FS-4956: Content updates from content review

---

app/blueprints/fund/forms.py
app/blueprints/round/forms.py
app/blueprints/round/routes.py
app/blueprints/round/services.py
app/shared/validators.py
tests/blueprints/fund/test_routes.py
tests/blueprints/round/test_forms.py
tests/blueprints/round/test_routes.py

**Ticket : https://mhclgdigital.atlassian.net/browse/FS-4967**
Adding validation error messages

FS-4967: Adding error messages 

---

app/all_questions/read_forms.py

When next is empty, it raises a StopIteration since it cannot find an object which is happy with the condition so if it did not find any return None
These errors happened due to a old bad data previously we had a feature to not to create a list component if there is a list with the same name so what happened was once you uploaded a wrong template Ex. half a list of local authorities and then if you upload the full list of local authorities then it will not update the list since name is already there so @wjrm500 did a change to fix and now even we have the list we create the list but unfortunately this test template was a older one before that fix so most of the values are not there so condition check fails and gives that error..
I suggest two work arounds 
1. delete data in test re create …

When next is empty, it raises a StopIteration since it cannot find an object which is happy with the condition so if it did not find any return None

---

app/blueprints/application/forms.py
app/blueprints/application/routes.py
app/blueprints/application/templates/section.html
tests/blueprints/application/test_routes.py

Ticket: https://mhclgdigital.atlassian.net/browse/FS-5008

FS-5008: Update application section form

---

app/blueprints/fund/templates/fund.html
app/blueprints/round/templates/round.html

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4967**
remove fieldset grouping since this tries to group the fields logically incorrectly 
Fix for the following comment
https://mhclgdigital.atlassian.net/browse/FS-4967?focusedCommentId=645719

FS-4967 : remove fieldset grouping since this tries to group the fields logically incorrectly 

---

app/blueprints/application/templates/build_application.html
app/blueprints/fund/templates/fund.html
app/blueprints/fund/templates/fund_details.html
app/blueprints/index/routes.py
app/blueprints/round/routes.py
app/blueprints/round/templates/round.html
app/blueprints/round/templates/round_details.html
app/blueprints/template/routes.py
app/blueprints/template/templates/template.html
app/blueprints/template/templates/template_details.html
app/blueprints/template/templates/view_template_questions.html
app/create_app.py
app/shared/page_tracker.py
app/templates/select_application.html
app/templates/select_fund.html
tests/blueprints/fund/test_routes.py
tests/blueprints/round/test_routes.py
tests/blueprints/template/test_routes.py
tests/conftest.py
tests/shared/test_back_link.py

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-5004**
Back button handling using sessions and here it will keep tack of the endpoints that we visit and accordingly it will go back once click on the back button in the UI

FS-5004 : replicate browser back button using sessions

---

app/blueprints/application/templates/build_application.html
app/blueprints/application/templates/view_questions.html
app/blueprints/fund/templates/fund.html
app/blueprints/fund/templates/fund_details.html
app/blueprints/round/templates/round.html
app/blueprints/round/templates/round_details.html
app/blueprints/template/templates/template.html
app/blueprints/template/templates/template_details.html
app/blueprints/template/templates/view_template_questions.html
app/templates/base.html
app/templates/select_application.html
app/templates/select_fund.html

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4973**
backlink fix and use one backlink every place but passing a boolean if backlink is needed

backlink fix and use one backlink every place but passing a boolean if backlink is needed

---

app/export_config/generate_fund_round_config.py
app/shared/data_classes.py
tests/test_config_export.py

https://mhclgdigital.atlassian.net/browse/FS-4913

FS-4913: fix non string for fund config export

---

app/blueprints/application/forms.py
app/blueprints/application/templates/section.html
app/shared/page_tracker.py
app/static/src/styles/fab.css

[Button placement, UI clarity and navigation updates](https://mhclgdigital.atlassian.net/browse/FS-5033) (this PR only covers the first part of the ticket, around the "Update Section" page)
- Adding back button
- Adding "Delete section" button
- Adding preview links to tasks
- Re-design of task actions (move up, move down, remove)
- Repositioning buttons and adding "Cancel" button
- Aligning content and layout with final design
Ensure deployed to dev environment ([I've done this](https://github.com/communitiesuk/funding-service-design-fund-application-builder/actions/runs/13566201583) but may have been overridden) then verify the following...
- Design matches Mika's from the FAB Figma
- Back button takes you to "Build application" page
- "Delete section" button deletes the section and …

FS-5033 - "Update section" changes

---

app/blueprints/application/forms.py
app/blueprints/application/templates/section.html

Fixing a inconsistency in the html and with this change it will be easy to identify the component based on the name in e2e

adding section template fix

---

app/blueprints/template/routes.py

When a user created the template and clicked on save and return home should go back to dashboard instead, it comes back to the template page

When a user created the template and clicked on save and return home should go back to dashboard instead, it comes back to the template page

---

copilot/fsd-fund-application-builder/manifest.yml

_Add ticket reference to Pull Request title: e.g. 'FS-123: Add content', if there is no ticket prefix with BAU_
add UAT communities alias
Should resolve but 404 on UAT after deployment

FSPT-228: add UAT communities alias

---

app/blueprints/round/routes.py

Fix flash message once created the application

Fix the flash message once created the application

---

app/all_questions/metadata_utils.py

Fix failing export

---

app/db/models/application_config.py
app/db/queries/clone.py
tests/unit/test_clone.py

Ticket : https://mhclgdigital.atlassian.net/browse/FS-5036
- [ x] README and other documentation has been updated / added (if needed)

FS-5036: Fix Clone Lizt object for cloned components

---

.github/workflows/copilot_deploy.yml

Trigger e2e once after test deployment
In the previous PR we are tying to implement e2e runing once after every merge and after deployment

Trigger e2e once after test deployment

---

app/blueprints/application/routes.py

**Ticket: https://mhclgdigital.atlassian.net/browse/FS-5034**
In this PR it will have success message when there is a update or addition happen into the application with sections 
Add a section & edit a section
section update 
section add

adding section update and addition status check flash message

---

app/blueprints/application/templates/section.html

adding the id for the add question template section since it has some CSS related to positioning & can be converted into a class since no repeating

Alignment fix

---

app/blueprints/index/routes.py

Adding a fix to allow the users to upload files in the preview mode

Adding a fix to allow the users to upload files in the preview mode

---

.github/workflows/copilot_deploy.yml

BAU - Updating deployment workflow name from 'Deploy to Test-UAT' to 'Deploy to Test-UAT-Prod' in light of introduction of prod env

---

app/static/src/styles/fab.css

[FLS-1419](https://mhclgdigital.atlassian.net/browse/FLS-1419) colour fix according to the gov uk standard and to fix the accessibility issue
[FLS-1419]: https://mhclgdigital.atlassian.net/browse/FLS-1419?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FLS-1419 colour fix according to the gov uk standard and to fix the accessibility issue

---

config/envs/development.py

FLS-1441 adding FSD_ADMIN into a DEBUG_USER role
PR reference : https://github.com/communitiesuk/funding-service-pre-award/pull/513

FLS-1441 adding FSD_ADMIN into a DEBUG_USER role
