communitiesuk/funding-service-design-fund-application-builder

app/blueprints/fund_builder/routes.py, app/blueprints/self_serve/templates/index.html, app/import_config/README.md, app/import_config/load_form_json.py, tasks/test_data.py
=> patch import script paths

app/blueprints/fund_builder/routes.py, app/db/queries/application.py, docker-compose-dev.yml, docker-compose.yml, tasks/db_tasks.py, tests/test_db_application_CRUD.py
When editing an application round, the following now happens:
- If you delete a form from a section, the DB rows for that form, it's pages and components are also deleted
- If you delete a section from the application, then the forms within that section, and all their children are also deleted
Create a round with multiple sections and forms within those sections
Delete a form and check it and its pages are deleted from the db
Delete a section and check it and it's forms are removed from the db
No UI changes as the behaviour was already present in the frontend but it was doing a soft delete so this change is backend only
=> fs-4642 adding cascade deletes

.devcontainer/python-container/devcontainer.json, app/blueprints/fund_builder/routes.py, app/blueprints/fund_builder/templates/build_application.html, app/blueprints/fund_builder/templates/section.html, app/db/models/application_config.py, app/db/models/round.py, app/db/queries/application.py, docker-compose.yml, tests/test_db.py
Allows the reordering of sections in a round and forms in a section. Also corrects the ordering of sections and forms when one is removed or cloned
Added move up/move down links to build application screen
Added move up/down links to section screen
=> Fs 4643 numbering

.devcontainer/devcontainer.json, app/blueprints/fund_builder/routes.py, app/export_config/helpers.py, config/envs/default.py, config/envs/development.py, config/envs/unit_test.py, tests/conftest.py, tests/test_config_export.py, tests/test_integration.py
FS-4724 was a bug where the export functionality didn't work on any AWS environments. We need to use a different path for writing the temp files to for creating the zip archive. Updated the file path to come from config rather than hard coded inside the app, using `/tmp` for deployed environments.
- Added a unit test to check zip creation
- Added a test fixture to cleanup the temp output dir and made existing tests use this
Create a fund and round and build an application (or use an existing one)
Go to 'Create Export Files for Round' and this should generate a zip file to download
=> Fs 4724 fix temp path

.github/workflows/copilot_deploy.yml
Updates to the github actions file:
- Change run name to 'Build and Unit Test' instead of 'Dev Deploy' to match other apps, and because we aren't auto deploying to dev
- Commented out post deploy tests as they don't relate to FAB and hold things up if they fail as they are unrelated
- Commented out prod deploy and removed from options as we are a long way from prod so don't need it there atm
=> Removing prod, tests that don't apply, and making name more accurate

app/blueprints/fund_builder/forms/round.py
Tiny tweak to add/edit round form:
- Contact textphone, telephone and email are now optional as COF doesn't have textphone or telephone
- Added 'en' to the fields that only need the English text at present
=> Making contact details optional

app/blueprints/fund_builder/forms/round.py, app/blueprints/fund_builder/routes.py, tasks/test_data.py, tests/test_config_export.py, tests/test_routes.py
Fixing the handling of json fields in the round so they export correctly for fund-store
Create or edit a round, observe `feedback_survey_config` and `eoi_decision_schema` are saved as valid json and can be edited as such
=> Fixing json export

app/export_config/generate_fund_round_config.py, tests/test_config_export.py
Updating the export filename for the fund_store config to use the fund_short_name as at the moment we need to manually rename this file for the fund loader
=> changing export filename to fund_short_code

app/export_config/generate_fund_round_config.py, app/export_config/helpers.py, config/envs/default.py, config/envs/development.py, tests/test_config_export.py
Adding extra config to the export from fab:
- Includes notify config to send email on submit. Uses the existing templates from COF25 so it doesn't crash (otherwise we have to create new templates in notify for every local fund we have)
- Includes config for assessment store so the import process works:
- Generates the assessment mapping for scored and unscored criteria so that every field in the application appears in assessment. It makes each form a sub criteria and each page a theme. It alternates between scored and unscored. So whilst it's not suitable for production it will be useful for setting up local (or dummy) funds for testing.
Usage of this output detailed here: https://mhclgdigital.atlassian.net/wiki/spaces/FS/pages/336298006/Setting+up+fab+-+apply+-+assess+locally
=> Bau add default assess config

.github/workflows/copilot_deploy.yml, copilot/fsd-fund-application-builder/manifest.yml
This will help us migrate from the "microservice"-y fund-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-108
Also removes the push path filters for the `copilot-deploy` workflow which are out of date and block pipelines being triggered on updates to key files eg. copilot manifest. If this leads to unnecessary builds we can add back some specific exclusions but it seems safer that way than explicit allow paths which will get out of date very quickly.
=> Read fund-store host from parameter store, remove push path filters for pipelines

docker-compose.yml
Changes to the Dockerfile to implement `uv` broke the dev container `docker-compose` file, so this removes the target that no longer exists.
=> Removing non existent target from compose file

copilot/fsd-fund-application-builder/manifest.yml
This will help us migrate from the "microservice"-y application-store to a more consolidated pre-award-stores service.
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-122
=> BAU: Move application store api host to AWS parameter store secret

copilot/fsd-fund-application-builder/manifest.yml
This is because the `recreate` deployment method leads to downtime, which can cause tests to flake. It is not any faster than a normal deployment, and causes tests to break. I am not sure why it was chosen to begin with.
https://aws.github.io/copilot-cli/docs/manifest/lb-web-service/#deployment-rolling
=> Turn off recreate deployment in test env

app/export_config/generate_fund_round_config.py, tasks/test_data.py
[Round fields not passed to export](https://mhclgdigital.atlassian.net/browse/FS-4876)
We noticed a bug whereby certain fields specified in the “Create a round” page of FAB are saved, but not passed to the export. This means that FAB-configured values for these values will have no effect in live services.
Specifically, the fields application_reminder_sent and eligibility_config are not exported.
=> FS-4876 - Ensure all round fields are passed to the round export

.github/workflows/copilot_deploy.yml, config/envs/unit_test.py, docker-compose.yml, docs/database.md, docs/run.md, tasks/db_tasks.py
[Fix local testing of FAB when using global Docker Runner](https://mhclgdigital.atlassian.net/browse/FS-4877)
Currently if we use the Funding Service-wide Docker runner to spin up apps locally, we get SQL connection issues when we try to run unit tests in FAB (uv run pytest .). This is because  these unit tests rely on the existence of a database fab_unit_test the global Docker Runner doesn’t provide this.
These changes are to rename from `fab_unit_test` to `fab_store_test` for consistency with the database name specified in [this PR](https://github.com/communitiesuk/funding-service-design-docker-runner/pull/100) and to change the environment variable name `DATABASE_URL_UNIT_TEST` to `DATABASE_URL_TEST` again for consistency with the database name and purpose.
=> FS-4877 - Fix local testing of FAB when using global Docker runner

config/envs/unit_test.py, docker-compose.yml, docs/database.md, docs/run.md, tasks/db_tasks.py
[Fix local testing of FAB when using global Docker Runner](https://mhclgdigital.atlassian.net/browse/FS-4877)
This PR - https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/130 - was intended to fix this problem, but it did not. This is because of a discrepancy between the database password required for locally running unit tests versus running them in GitHub. I ran the tests locally with the password `password` which worked, then pushed the code up. The code failed in GitHub, so I changed the password to `postgres`, forgot to re-test and pushed the code up, which then passed on GitHub, then merged 🤓 
Anyway this PR fixes that by using an env var `DATABASE_URL` where available (containing the password `postgres`) and a hard-coded string containing the …
=> FS-4877 - Ensuring FAB unit tests run both locally and in GitHub

app/blueprints/fund_builder/forms/round.py
[Make feedback and guidance links non-mandatory in "Create a Round"](https://mhclgdigital.atlassian.net/browse/FS-4867)
Feedback link and guidance URL are non-mandatory, therefore we should not mandate their collection in FAB.
=> FS-4867 - Make feedback and guidance links non-mandatory in 'Create a Round' form

app/blueprints/fund_builder/forms/round.py
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4872**
As per the request  `Support times`  field will change into -> 'Support Times for Applicants'
=> FS-4872: support time field name change

app/import_config/load_form_json.py, tests/test_form_import.py
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4882**
**Issue Summary**
In a given form, we have multiple pages, and on a given page, we have components, and some of those components can have a list attached, and in a given list we can have various items. Based on these items, we can create multiple conditions and conditions will be attached into only one component. According to the following example you can see in the field section `Which datasets have you collected?` question field is used several times because we have conditions for each list item. 
```
"conditions": [
{
"displayName": "conservation areas",
"name": "CNtvCT",
"value": {
"name": "conservation areas",
"conditions": [
{
"field": {
"name": "FjGMRE.PfjXKB",
"type": "CheckboxesField",
"display": "Which datasets have …
```
=> FS-4882: Fix for duplicate condition creation when the same condition

app/blueprints/fund_builder/routes.py, app/blueprints/fund_builder/templates/fund.html, app/blueprints/fund_builder/templates/round.html, app/blueprints/templates/routes.py, app/blueprints/templates/templates/edit_form_template.html, app/blueprints/templates/templates/view_templates.html, app/shared/helpers.py
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4848**
With this PR we are trying to add error banner for the following page 
1. Round create/update error banner handling
2. Fund create/update banner handling
3. Template management error handling
=> FS-4848: Error banner handling in fund create/edit page, round add/edit page, template management page

.idea/runConfigurations/FAB.xml, app/blueprints/fund_builder/forms/fund.py, app/blueprints/fund_builder/forms/round.py, app/shared/helpers.py
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4865**
In this ticket we are adding extra validation to check does any users try to put empty spaces between the short name while in fund creation/update and round creation/update
=> FS-4865: validating empty spaces between short names of the fund and round and also updating intelij idea setting

app/blueprints/fund_builder/routes.py, app/blueprints/self_serve/routes.py, app/blueprints/templates/routes.py
Returning to the index is problematic when running FAB locally, as users are never authenticated, rather authentication is bypassed with `DEBUG_USER` environment variables. Thus we observe behaviour such as user being redirected to login page after creating a fund. Again this only affects local development, as deployed FAB will enforce authentication.
=> BAU - Return to dashboard not index

copilot/fsd-fund-application-builder/manifest.yml
[Add basic auth to FAB for pre-prod environments](https://mhclgdigital.atlassian.net/browse/FS-4833)
Following the convention of other apps including [Authenticator](https://github.com/communitiesuk/funding-service-design-authenticator/pull/358/files), we can use an Nginx sidecar to seamlessly provide basic auth on all HTTP requests, while allowing requests to `/healthcheck` through.
We have only added to Dev and Test environments, not UAT as this will be our _de facto_ prod environment for the January delivery, and will be authenticated by Entra ID.
Note that we also need to ensure values are in the AWS Parameter Store to support this change.
=> FS-4833 - Adding basic auth to FAB

app/db/queries/application.py, app/import_config/load_form_json.py, tests/conftest.py, tests/test_config_import.py, tests/test_form_import.py
[Create new list for every form even where names collide](https://mhclgdigital.atlassian.net/browse/FS-4899)
Lists are scoped to forms. If two list-containing forms are loaded into FAB, even if those lists have the same name identifier, we should create two distinct lists in FAB, to preserve the data in those lists.
Currently, we do not do this. We check whether a list with the same name exists in the database, and if so we do not add the list.
This wouldn't be a practical problem if users created forms in isolation, as random identifiers are used for list names and these are unlikely to collide. The problem is that users clone forms, thereby cloning these random identifiers.
=> FS-4899 - Create new list for each form even where list name (ID) is the same

.idea/runConfigurations/FAB.xml, app/blueprints/fund_builder/forms/fund.py, app/blueprints/fund_builder/forms/round.py, app/blueprints/fund_builder/routes.py, app/blueprints/templates/routes.py, app/db/queries/fund.py, app/db/queries/round.py, app/shared/helpers.py, tests/test_routes.py
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-4895**
In this change we are focussing on fund and round short name reuse issue so following scenarios are acceptable 
1. If there is a fund and that given short name is not in our records that short name is acceptable 
2. If there is an update for the given fund short name is acceptable because it belongs to it self 
3. IF there is a fund and when round creation if the short name is not available then acceptable 
4. IF there is a different fund and we are planing to use same short name it is acceptable 
5. If we do update the round then it will be again acceptable since short name belongs to it self
Following are not acceptable 
1. If there is a fund for a given short name then we are shoving an error for validation purpose 
2. If …
=> FS-4895: When creating a fund or a round check, whether given round shortnames are available

app/blueprints/fund_builder/forms/fund.py, app/blueprints/fund_builder/forms/round.py, app/blueprints/fund_builder/routes.py, app/blueprints/fund_builder/templates/fund.html, app/blueprints/fund_builder/templates/round.html, app/templates/macros/wtfToGovUk.html
[Show or hide Welsh-specific fields depending on Welsh available toggle](https://mhclgdigital.atlassian.net/browse/FS-4861)
FAB users are asked on the “Create a Fund” page to specify whether Welsh is available for the fund. However, regardless of what they select, we show fields that are only relevant if the answer is yes (Welsh is available), e.g., “Description (Welsh)”. This clutters the interface unnecessarily.
To resolve this, we should only show Welsh-specific fields if Welsh is selected as available. We should do this for fields on both the “Create a Fund” and “Create a Round” pages. We should move the Welsh available toggle above all Welsh-specific fields so that the user flow makes sense.
Pre-requisites...
- For devs - checkout this branch, restart FAB Docker container locally
- …
=> FS-4861 - Show or hide Welsh-specific fields depending on Welsh available toggle

app/templates/base.html
Currently we have no page title at all as neither `service_title` nor `pageHeading` are set anywhere. The code is effectively broken. This is just a very quick and hopefully uncontroversial fix to set "Fund Application Builder" as the page title in the base template.
=> BAU - Add page title of 'Fund Application Builder' by default

app/export_config/generate_all_questions.py, app/export_config/generate_fund_round_html.py
We've moved apply, assess and authenticator into a single app. In doing so, to keep templates separate, we've namespaced them based on which app they came from.
So all apply frontend templates are now under the `apply/` prefix.
This fixes those template paths.
=> Fix template paths for pre-award-frontend

app/templates/base.html
[Change service title to Fund Application Builder](https://mhclgdigital.atlassian.net/browse/FS-4921)
- Spin up FAB locally using [Docker Runner](https://github.com/communitiesuk/funding-service-design-docker-runner)
- Open FAB at https://fund-application-builder.levellingup.gov.localhost:3011/dashboard
- Note the title "Fund Application Builder"
- Click the title
- You should be redirected to either [login](https://fund-application-builder.levellingup.gov.localhost:3011/login) or [dashboard](https://fund-application-builder.levellingup.gov.localhost:3011/dashboard), depending on whether you are authenticated
=> FS-4921 - Change service title to 'Fund Application Builder' and hyperlink it

Dockerfile
This prevents Renovate generating unnecessary PRs to update these digests. These PRs can be considered unnecessary as this Dockerfile is not used in production.
=> BAU - Remove specific SHA256 digests from Python base image and uv dependency

app/create_app.py, app/templates/500.html, tests/blueprints/index/test_routes.py
https://mhclgdigital.atlassian.net/browse/FS-4922
Adds default error handler to application to catch all internal server errors and render a new 500.html page, which looks like this:
=> FS-4922 - Handle 500 error gracefully with error page render

app/blueprints/application/routes.py, app/blueprints/fund/routes.py, app/blueprints/template/routes.py, app/templates/base.html
https://mhclgdigital.atlassian.net/browse/FS-4944
- Remove `govukBreadcrumbs` component from base.html
- Remove breadcrumb items from template params in all route functions that use them
**Fund Settings before:**
---
**Fund Settings after:**
---
**Build Application before:**
---
**Build Application after:**
=> FS-4944 - Remove breadcrumbs

pyproject.toml, uv.lock
https://mhclgdigital.atlassian.net/browse/FS-4945
- **Removing unused non-dev dependencies** - these dependencies are not used by the application and should be removed
- **Moving beautifulsoup4 dependency from dev dependency group to main project dependencies** - beautifulsoup4 is required for the application to function - it is imported in `app/all_questions/metadata_utils.py`, which is imported in `app/blueprints/application/routes.py` among other places
=> FS-4945 - Tidy dependencies

app/blueprints/application/routes.py, app/blueprints/fund/templates/fund_config.html, app/blueprints/index/templates/dashboard.html, app/blueprints/round/routes.py, app/blueprints/round/templates/round.html, app/db/models/fund.py, app/db/models/round.py, app/db/queries/fund.py, app/db/queries/round.py, app/templates/select_application.html, app/templates/select_fund.html, tests/blueprints/application/test_routes.py, tests/blueprints/round/test_routes.py
https://mhclgdigital.atlassian.net/browse/FS-4927
When accessing "Create a Round" or "Build Application" from the Home page, we need additional context in order to understand:
- For "Create a Round" - which fund we are creating a round for
- For "Build Application" - which application's tasklist we are modifying
Currently we get that context by:
- For "Create a Round" - by asking the user to select a fund from a drop-down at the top of the page
- For "Build Application" - by asking the user to select a fund and a round for that fund on the "View fund" page accessed via "Manage Application Configuration"
We are now changing the way we get that contextual information from the user. We are doing this with intermediary "Select" pages:
- For "Create a Round" - we show the user a page asking …
=> FS-4927 - Intermediary select pages

app/blueprints/fund/templates/fund.html, app/blueprints/round/templates/round.html, app/create_app.py, app/static/src/js/create_edit_fund.js, app/static/src/js/create_edit_round.js, app/templates/base.html, app/templates/head.html, build.py, config/envs/default.py, pyproject.toml, uv.lock
[FS-4947](https://mhclgdigital.atlassian.net/browse/FS-4947)
- **Remove unused Sortable.js** - Removed an unused script that was being loaded from an external CDN. We don't want to include it as a safe script source in our Flask-Talisman Content Security Policy (CSP)
- **Move inline JavaScript to files** - Replaced inline JavaScript with external file references in the templates for creating and editing Fund and Round and modified the static asset build process to handle this. When using Flask-Talisman, inline JavaScript necessitates adding script hashes to the CSP, which is not maintainable
- **Add Flask-Talisman** - Implemented Flask-Talisman with settings copied from [Pre-Award](https://github.com/communitiesuk/funding-service-pre-award/blob/main/config/envs/default.py). Replaced …
=> FS-4947 - Implement Flask-Talisman security headers

app/blueprints/application/forms.py, app/blueprints/application/routes.py, app/blueprints/round/routes.py, app/shared/forms.py, app/templates/select_application.html, app/templates/select_fund.html, tests/blueprints/application/test_routes.py, tests/blueprints/round/test_routes.py, tests/helpers.py
https://mhclgdigital.atlassian.net/browse/FS-4927
This change is to render standard GOV.UK error UI components on the intermediary "Select fund" and "Select application" pages in the event of errored input, instead of the current default notification from front-end required validation. To do this, we need to render and validate actual Flask WTF forms.
=> FS-4927 - Adding error summary and errored field error decoration to intermediary 'Select fund' and 'Select application' pages

app/blueprints/fund/routes.py, app/blueprints/fund/templates/grant_details.html, app/export_config/generate_fund_round_form_jsons.py, tests/blueprints/fund/test_routes.py
Ticket: https://mhclgdigital.atlassian.net/browse/FS-4935
1. In this Ticket grant_details API is added to render the fund/grant created.
1. Use FAB
3. Create a fund
4. Try render the fund using url ex:
<FAB_URL>/funds/details?grant_id=<fund_id>
ex: https://fund-application-builder.levellingup.gov.localhost:3011/funds/details?grant_id=f9aa36e3-d42e-4416-9113-bd47dbd0a6f3
=> FS:4935: Grant details template and API

app/templates/base.html, config/envs/default.py, copilot/fsd-fund-application-builder/manifest.yml, tests/blueprints/index/test_routes.py
Ticket : https://mhclgdigital.atlassian.net/browse/FS-4950
Add Sign out functionality for FAB.
1. Internal users authenticated can now signout using Sign out link available in header.
2. Sign out is available in all pages with in FAB from Header only After user is logged in
- [x ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
1. Use FAB
2. Login to FAB 
3. Sign out link is available for the user to logout
4. Once the user clicks on  Sign out , user is logged out and  redirect to Authenticator login page, on login it redirects to FAB Dashboard/Home page
=> FS:4590- Implement Signout for FAB

.github/workflows/copilot_deploy.yml
Deploys to test & UAT will now trigger a Slack notification if the deployment fails as this would constitute a 'block' in the pipeline.
Relies on https://github.com/communitiesuk/funding-service-design-workflows/pull/231
Ticket: https://mhclgdigital.atlassian.net/browse/FSPT-220
=> FSPT-220: Enable Slack notification on failed deploys

app/blueprints/index/templates/dashboard.html
Fix for the issue pointed out by @tejvath on this ticket: https://mhclgdigital.atlassian.net/browse/FS-4925
Basically we weren't rendering HTML in the notification banner on the dashboard properly.
We can test this by creating a new fund, clicking "Save and return to home", and checking that the HTML content in the notification banner at the top of the dashboard is rendered as HTML, not text.
=> Bugfix - rendering HTML in notification banner properly

app/blueprints/fund/routes.py, app/blueprints/fund/services.py, app/blueprints/fund/templates/fund_details.html, tests/blueprints/fund/test_routes.py
Ticket: https://mhclgdigital.atlassian.net/browse/FS-4935
In this Ticket grant_details API is added to render the grant details when clicked on grant name in Grants list page.
1. Use FAB
2. Create a fund/grant
3. Click on Grants menu to list all grants.
4. Click on one of the Grant name , This will render a grant detail page.
ex: https://fund-application-builder.levellingup.gov.localhost:3011/grants/details?grant_id=f9aa36e3-d42e-4416-9113-bd47dbd0a6f3
5. Clicking on Back button should redirect to Grants list page.
6. Clicking on change link for the field will redirect to …
=> FS-4935: Grant details template and API 

app/templates/base.html
Guidance for this component says that when it's used beneath a GOV.UK Header, we need to set the header border (the blue bar) to be full width.
https://design-system.service.gov.uk/components/service-navigation/
=> Fix GOV.UK Service navigation implementation

app/blueprints/fund/routes.py, app/blueprints/fund/templates/view_all_funds.html, app/blueprints/round/routes.py, app/blueprints/round/templates/view_all_rounds.html, app/blueprints/template/routes.py, app/blueprints/template/templates/partials/view_template_page_description.html, app/blueprints/template/templates/partials/view_templates_details_description.html, app/blueprints/template/templates/view_templates.html, app/shared/generic_table_page.py, app/shared/table_pagination.py, app/templates/macros/genericTablePage.html, app/templates/macros/tablePagination.html, tests/blueprints/fund/test_routes.py, tests/blueprints/round/test_routes.py, tests/shared/test_generic_table_page.py
The GenericTablePage class/macro is doing too much and is making it difficult to accurately reproduce the designs and content.
This reduces the scope of the GenericTablePage component to only look after the table and its pagination. The rest of the template is now added into each page’s template, and this shouldn't massively increase overhead as we only have 3 of these page types.
This PR also removed the 'details' component from the View all Grants/View all Applications pages, as per the latest designs (see screenshots below).
[Jira ticket FS-4953](https://mhclgdigital.atlassian.net/browse/FS-4963)
=> FS-4963: Refactor generic table page macro

app/blueprints/template/routes.py, app/blueprints/template/services.py, app/blueprints/template/templates/template_details.html, tests/blueprints/template/test_routes.py, tests/seed_test_data.py
**Ticket : https://mhclgdigital.atlassian.net/browse/FS-4966**
This PR will cover the view items page for the uploaded templates
Go to the templates -> click one of the uploaded templates then you should see the details of the templates
also if you preview it should allow you to preview it in runner
=> FS-4966: View templates and view templates details page

build.py
Caught in QA of https://mhclgdigital.atlassian.net/browse/FS-4947
Precompiled GOV.UK Frontend html and css expects some assets (eg images, fonts, manifest) to be located at specific URL paths. We could only change this by bundling GOV.UK frontend ourselves, or doing some extremely gross search+replace in the bundled assets.
Instead of both of those, we can just lift the assets into the correct place for our local static files.
=> Move some assets to top of static dir for GOV.UK Frontend

app/blueprints/application/routes.py, app/blueprints/fund/routes.py, app/blueprints/fund/templates/fund.html, app/blueprints/fund/templates/view_all_funds.html, app/blueprints/round/routes.py, app/blueprints/round/templates/round.html, app/blueprints/round/templates/view_all_rounds.html, app/blueprints/template/routes.py, app/blueprints/template/templates/edit_form_template.html, app/blueprints/template/templates/view_templates.html, app/shared/helpers.py, app/templates/select_application.html, app/templates/select_fund.html, tests/blueprints/fund/test_routes.py, tests/blueprints/round/test_routes.py
Let's remove some more of our custom code and rely on govuk-frontend-wtf to do the heavy and consistent lifting.
Visually everything should be unchanged, except some error messages which no longer have the <field_name> prefix. We have [a ticket to rationalise all error messages](https://mhclgdigital.atlassian.net/browse/FS-4967) later, so I'm ok with this.
=> Replace custom error handling with govuk-frontend-wtf

app/blueprints/application/routes.py, app/blueprints/application/templates/build_application.html, app/blueprints/round/templates/round_details.html
Brings the 'Build Application' page in line with the frozen designs in Figma as per [Jira ticket 4938](**url**).
Also adds relevant behaviour to the 'back' link to redirect to the View Applications page or to the relevant Application Details page.
=> FS-4938: Update Build Application page

app/blueprints/round/forms.py, app/blueprints/round/routes.py, app/blueprints/round/templates/round.html
https://mhclgdigital.atlassian.net/browse/FS-4974
Removes our custom handling for rendering form fields and switches to using govuk-frontend-wtf widgets.
Adds `novalidate` to the form to disable HTML5 validation.
=> Standardise rendering of round page

app/blueprints/fund/routes.py, app/blueprints/index/templates/dashboard.html, app/blueprints/round/forms.py, app/blueprints/round/routes.py, app/blueprints/round/services.py, app/blueprints/round/templates/round.html, app/blueprints/round/templates/round_details.html, tests/blueprints/round/test_routes.py
Ticket: https://mhclgdigital.atlassian.net/browse/FS-4970
PR updating Application add and update api and templates
1. Create an application from Dashboard.
2. Back link should redirect to page form where it is initiated( works like browser backlink) --- select grant
3.Below actions can be tested on "Create a new application" page
1. Save and Continue should navigate to 
a. Design /Build Application page if it is initiated from Home with a success banner message.
b. Application list page if it is initiated from Applications list page with success banner message.
2. Save and …
=> FS-4970: Update Application add and edit api and template

app/blueprints/round/forms.py, app/blueprints/round/templates/round_details.html, tests/blueprints/round/test_routes.py
Fix the Application round label  and remove validations for optional EOI field.
-
1. Create a application with empty EOI schema json , Application should be created
2. Create a application with a string (  Non Json) data , should render a form error "**There is a problem
[Content is not valid JSON. Underlying error:**"
3. Update a application with empty EOI schema json , Application should be updated
2. Update a application with a string (  Non Json) data , should render a form error "**There is a problem
[Content is not valid JSON. Underlying error:**"
=> Bugfix: fix application field labels and optional field validations

app/blueprints/application/forms.py, app/shared/forms.py, app/templates/select_application.html, app/templates/select_fund.html
Ticket: https://mhclgdigital.atlassian.net/browse/FS-5007
Updated label for select fund and application with visually hidden text.
- [x ] README and other documentation has been updated / added (if needed)
=> FS-5007: Fix select fund and application label

.github/workflows/copilot_deploy.yml
This differs from the `notify_slack` setting, which is more like `alert_slack_on_failed_deployments`.
I'll maybe rename this separately...
Related:
https://github.com/communitiesuk/funding-service-design-workflows/pull/265
=> Enable slack deployment notifications

app/blueprints/application/templates/build_application.html
This makes consistent the 'preview template' behaviour on the template details page, and avoids users getting stuck on the form runner preview (which also includes a back link and top navigation that is specific to the runner/apply and not FAB).
Go to 'Build application' of an application that has a section and a template added (or create one and add a section and template). Click 'Preview' on that template on the 'Build Application' page. It should open in a new browser tab.
=> BAU: Build Application template preview open in new tab

copilot/fsd-fund-application-builder/manifest.yml
We don't deploy form designer in the UAT environment :upside-down-face:
So we just get an error
=> Point FAB UAT at test designer

app/blueprints/application/routes.py, tests/blueprints/application/test_routes.py
BAU : bugfix for redirection after adding template form to a section
=> Bugfix : fix redirect after adding template to update section

app/blueprints/fund/templates/fund_details.html, app/blueprints/round/templates/round_details.html, tests/blueprints/fund/test_routes.py, tests/blueprints/round/test_routes.py
Ticket : https://mhclgdigital.atlassian.net/browse/FS-4993
Add "Not provided" for empty optional fields in grant and application details,
- [x ] Commit messages are meaningful and follow good commit message guidelines (e.g. "FS-XXXX: Add margin to nav items preventing overlapping of logo")
=> FS-4993: Add Not provided for optional empty values in grant and application details

app/db/queries/application.py
fix form template table bug and here we have added accidentally default number of items pages to 5 and it should be 20 in the template page
=> fix form template table bug

app/blueprints/template/templates/view_all_templates.html, tests/unit/blueprints/template/test_routes.py
[Button placement, UI clarity and navigation updates](https://mhclgdigital.atlassian.net/browse/FS-5033) (this PR only covers the second part of the ticket, around the "Templates" page)
- Replacing "Edit details" button with "Preview in a new tab"
=> FS-5033 - Templates table - replace "Edit details" buttons with "Preview in a new tab"

app/blueprints/application/templates/section.html
[Button placement, UI clarity and navigation updates](https://mhclgdigital.atlassian.net/browse/FS-5033)
The previous [PR for modifying the "Update section" page](https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/297) had an unintended side-effect - it removed the "Save" button from the "Create section" page, which is rendered from the same Jinja2 template. See screenshot below:
This PR addresses that. It also takes the liberty of going one step further, and replacing the old "Save" button with a "Save and continue" button, with a "Cancel" button added for good measure, for consistency with the updates to the "Edit section" page. @mikaelmetthey - if you would prefer to revert to simply having a "Save" button, then that's also fine - I'll make that …
=> FS-5033 - Re-adding missing action buttons on "Create section" page

copilot/fsd-fund-application-builder/manifest.yml, tests/e2e/conftest.py
Config changes to move dev environment to communities.gov.uk domain
After deployment service should resolve at: https://fund-application-builder.access-funding.dev.communities.gov.uk and work as before (assuming accompanying pre-award changes have also been deployed)
=> FSPT-228 communities domain

app/blueprints/application/templates/build_application.html, tests/unit/blueprints/application/test_routes.py
[Button placement, UI clarity and navigation updates](https://mhclgdigital.atlassian.net/browse/FS-5033) (this PR only covers the third part of the ticket, around the "Build application" page)
- Replaced section action links with "Down" / "Up" links and "Edit" button, matching section.html styling
- Made task names clickable links opening previews in new tabs, removing separate "Preview" link
=> FS-5033 - "Build application" page design changes

app/blueprints/application/routes.py
[Button placement, UI clarity and navigation updates](https://mhclgdigital.atlassian.net/browse/FS-5033) (this PR only covers the third part of the ticket, around the "Build application" page)
This is a minor tweak to [an already-merged PR](https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/308) in response to [QA review](https://mhclgdigital.atlassian.net/browse/FS-5033?focusedCommentId=655907). The only change here is:
- Reset "Add a task" dropdown to "Select a template" after adding a task to a section
=> FS-5033 - Reset "Add a task" dropdown to "Select a template" after adding a task to a section

pyproject.toml, uv.lock
[Appropriate Authenticator content for FAB users when missing role](https://mhclgdigital.atlassian.net/browse/FS-5043)
This dependency update means we pass a new `source_app` parameter through to Authenticator to get FAB-specific content when a user is missing a required role.
See fsd-utils PR: [Add source_app parameter to _failed_roles_redirect](https://github.com/communitiesuk/funding-service-design-utils/pull/222)
And Authenticator PR: [FS-5043 - Adding FAB-specific error content in Authenticator when user is missing required role](https://github.com/communitiesuk/funding-service-pre-award/pull/313)
=> FS-5043 - Updating fsd-utils dependency 

app/blueprints/application/routes.py, app/blueprints/round/routes.py, app/templates/select_fund.html
Fixes the behaviour of the 'Cancel' button on the 'Select Fund' page
E.g., if we come from 'Applications table' page, we want 'Cancel' to send us back there (as per request from designers).
- Checkout this branch and spin up FAB locally
- Navigate to the [Applications page](https://fund-application-builder.levellingup.gov.localhost:3011/rounds/) and click "Create new application"
- Click "Cancel" on the [Select Fund page](https://fund-application-builder.levellingup.gov.localhost:3011/rounds/select-grant?action=applications_table) and verify it returns to the Applications page
- Navigate to the [Dashboard](https://fund-application-builder.levellingup.gov.localhost:3011/dashboard) and click on "2. Set up a new application"
- Click "Cancel" on the [Select Fund …
=> Fixes the behaviour of the 'Cancel' button on the 'Select Fund' page

app/create_app.py, tests/unit/conftest.py
[Add role-based auth to FAB](https://mhclgdigital.atlassian.net/browse/FS-5044)
Users must be a member of the "FSD_ADMIN" group in Azure AD to authenticate for FAB, as per TDA requirements.
*Pre-requisites*
- Get the Funding Service repos cloned locally (see [Docker Runner](https://github.com/communitiesuk/funding-service-design-docker-runner))
- Checkout this branch in FAB repo
*Auth success*
- Request to myself or Gideon that you are added to the "FSD_ADMIN" group on the test Azure AD tenant
- Spin up database, FAB and Pre-Award containers locally
- Go to https://fund-application-builder.levellingup.gov.localhost:3011/ in your browser (preferably in an incognito window to avoid any previous auth state)
- Sign in with your Microsoft credentials
- Confirm that you end up landing on the …
=> FS-5044 - Add role-based auth to FAB

copilot/fsd-fund-application-builder/manifest.yml, tests/e2e/conftest.py
Config changes to move test to communities domain name
After deployment service should be available on the test.communities.gov.uk domain name
=> FSPT-228: Move test to communities domain name

copilot/fsd-fund-application-builder/manifest.yml
Let's monitor uat (FAB's current "prod") at 100%, because those are likely to provide more realistic insights (and if there are errors, more information to help debug). The volume there is also significantly lower, so we should not have to worry about hitting our allowances.
=> Set sentry traces sample rate

.github/workflows/copilot_deploy.yml, .github/workflows/test_e2e_aws.yml
**Ticket: https://mhclgdigital.atlassian.net/browse/FS-5030**
Implementing e2e test running after deploying to dev and test environments
After having the discussion with @wjrm500 we have decided to brake this FS-5030 into two sub sections and it is already mentioned in this [comment](https://mhclgdigital.atlassian.net/browse/FS-5030?focusedCommentId=658274)
Once changes are merged into main and docker images is deployed to dev then after that if the e2e run is enabled then this changes will handle the e2e run process against the dev environment & also same for the test once changes are deployed to test it will run the e2e against test environment 
Following is one of the testing done by my self : https://github.com/communitiesuk/funding-service-design-fund-application-builder/actions/runs/ …
=> FS-5030: Implementing e2e test running after deploying to dev and test environments

.github/workflows/copilot_deploy.yml
Fix dependency chains in deployment workflow. Specifically, we have made unit tests a dependency of the build step and leveraged dependency hierarchies to simplify configuration.
=> Adding a fix for the CICD flow chain

app/blueprints/application/templates/build_application.html, app/blueprints/application/templates/section.html, app/static/src/styles/fab.css, app/templates/macros/search.html
generalising some css changes into a class since those are repeated changes among components & most of them are under ID selection and now it is logically invalid now to use that selection
=> Convert common css into a class & adding the changes into html

copilot/fsd-fund-application-builder/manifest.yml
Move UAT to communities domain
We can share most variables as config is now consistent between pre-prod environments (except that UAT points to test designer deliberately
Should resolve and function as intended at `https://fund-application-builder.access-funding.uat.communities.gov.uk` post-deployment
=> FSPT-228: Move UAT to communities domain

.github/workflows/copilot_deploy.yml
An attempt was made to simplify the dependency chain in `copilot_deploy.yml` recently but it missed the fact that jobs in this workflow rely on taking outputs directly from their dependencies e.g., via `needs.setup.outputs.jobs_to_run`.
This caused breakages, so these dependencies should be restored.
=> Fix - re-adding necessary GitHub workflow dependencies

.github/workflows/copilot_deploy.yml, .github/workflows/test_e2e_aws.yml
We are missing job names on our GitHub workflow jobs, meaning that we are forced to use whatever label we've assigned to the job in the code e.g., `dev_deploy`.
This PR adds human-readable names to all jobs.
=> Adding simple names to all GitHub workflow jobs for readability

.github/workflows/copilot_deploy.yml, .github/workflows/validate_pr.yml, tests/conftest.py, tests/e2e/conftest.py
**Ticket:  https://mhclgdigital.atlassian.net/browse/FS-5020**
When user creates a PR it should run the e2e locally inside GitHub actions and verify the changes are not going to brake any of the user journeys 
**Why we did not used the packito image ?**
when we install that in the AWS environment then that environment has the access level needed to run mkdir, file move etc.. but when we start the container inside the Github it gives a permission denied error
also there is no much difference the way that we star the app since we use the developed code & sole purpose to check the code works according to the user flows
**What changes that have implemented ?**
starting the Postgres sql in the GitHub workflow and apply the db changes finally start app & run against local environment
=> Run e2e test against pr to verify the changes

pyproject.toml
Fix issue where Renovate updates Playwright Docker tags in workflow files without updating the corresponding Python package version. This caused E2E test failures when the Docker container (v1.51.1) and Python dependency (v1.47.0) versions became mismatched - see PR: https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/346
By explicitly including playwright in our dependencies, Renovate can track and update it properly, ensuring version consistency between our Docker environment and Python dependencies.
=> Add playwright as direct dependency in pyproject.toml

app/blueprints/application/templates/application_complete.html, tests/unit/blueprints/application/test_routes.py
[Iterate 'mark as completed' confirmation page content](https://mhclgdigital.atlassian.net/browse/FS-5053)
Content changes as per ticket.
=> FS-5053 - Iterate content on 'Mark as complete' confirmation page

app/blueprints/application/templates/build_application.html
[Mark application as complete](https://mhclgdigital.atlassian.net/browse/FS-4954)
The 'Build application' page is much simplified when there are no sections in an application. The following elements are hidden:
- "Status: X" text
- "Download application ZIP file" button
- "View all application questions" button
- "Mark application complete" button
This should have been implemented as part of the original work on 'Mark application as complete' but was overlooked.
=> FS-4954 - Simplifying the 'Build application' page when there are no sections in an application

.github/workflows/copilot_deploy.yml
[Prevent outdated GitHub workflows running (FAB)](https://mhclgdigital.atlassian.net/browse/FS-5063)
If a previous deployment hasn't been cancelled, when you try to manually approve a later deployment, you can be silently switched to the previous workflow run, making accidental deployment of outdated workflow runs a significant hazard.
This change puts each deployment job (Dev, Test and UAT) in concurrency groups (e.g., "deploy-dev"), meaning that when they begin to run, existing deployments to the corresponding environment in previous workflow runs will be automatically cancelled, which should in theory prevent the weird behaviour described.
See [concurrency](https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#concurrency) section of GitHub Actions …
=> FS-5063 - Adding concurrency group to deployment jobs in GitHub workflow to prevent accidental deployment from outdated workflow runs

app/all_questions/metadata_utils.py
Ticket : https://mhclgdigital.atlassian.net/browse/FS-5069
Test:
1. check About your organisation template for "About your organisation CFA" .
2. View template questions was having issue rendering the Summary page title in between question which is now fixed.
**All questions from UAT**
**All questions rendered after fix**
=> FS-5069: Fix all questions rendering not rendering summary page info

.github/workflows/copilot_deploy.yml, app/blueprints/index/routes.py, config/envs/default.py, copilot/fsd-fund-application-builder/addons/fsd-fund-application-builder-cluster.yml, copilot/fsd-fund-application-builder/manifest.yml
[Putting FAB in production environment](https://mhclgdigital.atlassian.net/browse/FS-4810)
We are deploying FAB into production. FAB has been used by users since January, but the top level env has always been UAT. Once we get out to production, we need to restore a dump of the UAT database into production and notify users of the switchover. 
Before converting this PR out of draft, we need to..
Before deploying to UAT, we should ensure we take a dump of the UAT database. This is because we will be deploying out a CloudFormation stack change to this env for the first time. We have already tested this stack change on Dev and there were no issues, but good to take precautions and we need to dump UAT regardless.
=> FS-4810 - Putting FAB into production

.github/workflows/copilot_deploy.yml
@gidsg recently added protection rules to Pre-Award to prevent manual deployment to every environment except Dev, following the issue where an out-of-date manifest file was deployed and brought the Test environment down.
We should implement the same branch protection rules in FAB. Alongside this, we should ensure that the workflow dispatch (accessible via GitHub Actions tab) does not suggest that manual deployment to any env other than Dev is possible. The supposedly available options are enumerated in the workflow file.
=> Allow manual deploy via GitHub workflow dispatch only to Dev env

.github/workflows/copilot_deploy.yml
Currently we can manually deploy branches to each of the Dev, Test and UAT AWS environments via the Actions tab in the GitHub UI, by clicking Deploy to AWS -> Run workflow. The prod environment was recently introduced to FAB, and we should add that as a manually deployable environment. This is in-keeping with the approach taken in the Pre-Award repo.
_Note: the [original PR](https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/379) for this change was closed as we thought we'd discovered that the rule introduced by Gideon prevented manual deployment, when in fact it just limits deployment to main branch._
=> Allow manual deployments to prod via GitHub workflow dispatch

.github/workflows/copilot_deploy.yml
E2E tests in FAB have proven flaky, despite attempted wrangling. They fail intermittently. They shouldn't therefore be a deployment dependency. Instead we can have each deployment job depend on the deployment to the environment just below, creating a chain of deployments or promotions up through the environments.
=> Removing the E2E test dependency for UAT and prod deploy jobs

app/blueprints/application/routes.py, app/blueprints/template/routes.py, app/shared/forms.py, app/static/src/styles/fab.css, app/templates/delete_confirmation.html, tests/unit/app/blueprints/application/test_routes.py, tests/unit/app/blueprints/template/test_routes.py
Ticket: https://mhclgdigital.atlassian.net/browse/FS-4855
1. Delete confirmation is added when a template is deleted  or Application section is deleted.
1. Delete section:
a. On the ‘Build application’ page, users press ‘Edit’
b. On the ‘Update section’ page, users press ‘Delete section’
c. Users see an Confirmation page (Delete section) and confirm
d. Users return to the updated ‘Build application’ page (section deleted)
2. Delete template:
a.On the ‘Template details’ page, users press ‘Delete template’
b. Users see an Confirmation page (Delete template) and confirm
c.Users return to the updated ‘Templates table’ page (template deleted)
=> FS-4855: Add delete confirmation for application form section and template

copilot/fsd-fund-application-builder/manifest.yml
[Add basic auth to FAB UAT environment](https://mhclgdigital.atlassian.net/browse/FLS-1131)
The UAT environment configuration was updated to include an Nginx sidecar container, routing incoming traffic through it (`target_container: nginx`) to enforce "basic auth" before proxying requests to the main application on port 8080.
=> FLS-1131 - Add basic auth to FAB in UAT environment

.idea/runConfigurations/FAB.xml, config/envs/default.py, tests/e2e/conftest.py
This PR on Docker Runner - [Migrate from levellingup to communities domain](https://github.com/communitiesuk/funding-service-design-docker-runner/pull/137) - means that we now run apps locally at communities.gov.uk, not levellingup.gov.uk. However, E2E tests in FAB refer to levellingup.gov.uk, which means when you try to run E2E tests locally for FAB, they simply don't work. This fixes that.
=> Use communities.gov.uk domain when running E2E tests locally

.github/workflows/copilot_deploy.yml
Ticket: https://mhclgdigital.atlassian.net/browse/FLS-1235
- E2E check was disabled for UAT and PROD deploys because they were flaky, but now that they are fixed we should add the checks back in
=> FLS-1235: Add e2e check back for UAT and PROD deploy

copilot/fsd-fund-application-builder/manifest.yml
Need to store ALLOWED_DOMAINS as a secret not a variable in the AWS Copilot manifest (manifest.yml) otherwise the reference to the secrets location is passed as a useless string to the app.
=> Move ALLOWED_DOMAINS from variables to secrets

app/blueprints/index/routes.py, config/envs/default.py, copilot/fsd-fund-application-builder/manifest.yml
[Tear down the UAT (or test?) environment](https://mhclgdigital.atlassian.net/browse/FSPT-342)
- **Preview forms using Form Runner in Test env not UAT**
We are wanting to remove the UAT environment as it is an unnecessary expense. We therefore need to decouple FAB in production from Form Runner in UAT so that when we remove UAT, FAB in production won't be affected in any way. Prod FAB is tied to UAT Runner because Prod Runner does not allow requests to the `/publish` endpoint required for previewing forms. This is intended as a temporary measure to unblock UAT environment shutdown. Longer-term we will look to link Prod FAB to Prod Runner.
- **Support Form Runner basic auth**
Form Runner is having basic auth added to it, as a compromise given we need to remove JWT auth from certain Runner …
=> FSPT-342 - Use Test Runner (instead of UAT) for form preview

app/blueprints/fund/forms.py, tests/unit/app/blueprints/template/test_routes.py
[Ensure visually hidden prefix text is accessible to screen readers or remove it from the example input.](https://mhclgdigital.atlassian.net/browse/FLS-1416)
The "Application name" field on /grants/create had duplicate "Apply for" text for screen reader users:
- Visual prefix shows "Apply for" (hidden from screen readers with aria-hidden="true")
- Field description said "For example, Apply for funding to save an asset..."
- Screen readers heard the description but not the prefix, causing potential duplication
Removed "Apply for" from field descriptions to prevent duplication.
Before: "For example, Apply for funding to save an asset in your community"
After: "For example, funding to save an asset in your community"
Visual users see no change, screen reader users no longer get duplicate …
=> Fix screen reader accessibility issue with "Apply for" prefix

config/envs/default.py
Need to use HTTPS because Runner expects HTTPS. And need to use external rather than internal hostname to avoid hostname mismatch.
When FAB tries to publish forms to Form Runner, it was using the HTTP protocol and internal service name (`http://form-runner:3009/publish`). However, Form Runner is configured to use HTTPS with SSL certificates issued for the external domain `form-runner.communities.gov.localhost`. 
This caused two issues:
1. Protocol mismatch: HTTP requests to an HTTPS service resulted in SSL handshake errors
2. Hostname mismatch: SSL certificate verification failed because the certificate is valid for `form-runner.communities.gov.localhost`, not the internal service name `form-runner`
This change aligns FAB's configuration with Pre-Award, which already uses the correct …
=> FLS-1444 - Fixing default Form Runner publish URL

app/blueprints/template/routes.py, app/db/queries/application.py, app/import_config/load_form_json.py, tests/unit/app/blueprints/template/test_routes.py, tests/unit/app/db/queries/test_application.py
[Update interfaces for insert and update form functions](https://mhclgdigital.atlassian.net/browse/FLS-1462)
**Commit 1 - Adjusting insert_new_form function interface**
Currently, `insert_new_form` takes an arg `new_form_config` which is an untyped dict with an implicit schema. `insert_new_form` is only called in one place (`insert_form_template` in `app.import_config.load_form_json`) and there we pass static values for five of the nine dict keys.
This commit simplifies and normalises the interface of `insert_new_form`, passing specific args instead of a schema-less dict.
**Commit 2 - Adjusting update_form function interface**
Currently, `update_form` takes an arg `new_form_config` which is an untyped dict with an implicit schema. `update_form` is only called in one place (`edit_template` …
=> FLS-1462 - Update interfaces for insert and update form functions

app/import_config/load_form_json.py
There is a bug whereby we are adding `filename` to the form JSON after validation but before we store the JSON in the `form_json` column. `filename` is a key rejected by the Form Runner. Thus the addition of this key invalidates the JSON.
In this PR, we move the addition of the filename to the dict to after the insertion of the form JSON in the database, to avoid this issue with minimal code changes.
=> Don't add filename to form JSON until after it's been inserted into form_json column

app/export_config/generate_fund_round_form_jsons.py, app/import_config/load_form_json.py, tests/conftest.py, tests/integration/test_integration.py, tests/seed_test_data.py, tests/test_data/org-info.json, tests/unit/app/blueprints/template/test_routes.py, tests/unit/app/export_config/test_generate_fund_round_form_jsons.py, tests/unit/app/import_config/test_load_form_json.py
[Start using whole form JSON for forms export](https://mhclgdigital.atlassian.net/browse/FLS-1466)
As part of the export process in FAB, whereby we generate a ZIP file full of Pre-Award and Form Runner config, we re-build all of the funding round’s form JSONs at runtime from the sets of relational entities we decomposed JSON files down into at import (see `generate_form_jsons_for_round` in `app.export_config.generate_fund_round_form_jsons`). Put another way, we call the `build_form_json` function.
We are moving away from relational form entities in FAB. Now we are storing whole form JSON directly, we can simply replace the `build_form_json` call with direct access to the `Form` model’s `form_json` attribute.
- All relevant tests have been updated
- To test yourself...
- Run FAB locally …
=> FLS-1466 - Start using whole form JSON for forms export

app/export_config/generate_assessment_config.py, tests/unit/app/export_config/test_generate_assessment_config.py
[Start using whole form JSON for assessment config export](https://mhclgdigital.atlassian.net/browse/FLS-1476)
As part of the export process in FAB, whereby we generate a ZIP file full of Pre-Award and Form Runner config, we generate a minimal assessment config, grouping questions into assessment criteria, subcriteria and themes using a naive mapping from the application config (section → criteria, form → subcriteria, page → theme). This process is tightly coupled to FAB’s relational forms storage model, leveraging ORM-powered syntax.
We are moving away from relational form entities in FAB. Now we are storing whole form JSON directly. We therefore need to rewrite the assessment config generation logic so that it works with whole JSON blobs, in order to avoid a functional regression.
This …
=> FLS-1476 - Use whole form JSON for assessment config export

tests/e2e/pages/build_application_page.py
E2E tests were failing intermittently with Playwright strict mode violations when randomly generated section names (like "at") caused `get_by_role("heading", name=section_name)` locators to match both the intended section heading "2. at" and the main page heading "Build application" (which contains "at"). This fix updates all section-related locators to use specific CSS selectors targeting the task list structure instead of generic heading role lookups, eliminating the ambiguity and making the tests more robust.
=> Resolve ambiguous locators in E2E tests causing intermittent failures

app/blueprints/application/routes.py
[Start using whole form JSON for all questions HTML endpoints](https://mhclgdigital.atlassian.net/browse/FLS-1465)
We forgot to swap out the `build_form_json` call in the `view_form_questions` endpoint in the [original PR that covered this ticket](https://github.com/communitiesuk/funding-service-design-fund-application-builder/pull/440).
=> FLS-1465 - Start using whole form JSON for 'View form questions' endpoint

app/shared/helpers.py
🎫 Ticket
[Clean up application code](https://mhclgdigital.atlassian.net/browse/FLS-1470)
The get_all_pages_in_parent_form function in app/shared/helpers.py is no longer needed after the transition to using form_json. This function was querying the old Page ORM model directly, but with form_json, pages are accessed directly from the JSON structure instead.
- Remove get_all_pages_in_parent_form function
- Remove unused from app.db.models import Page import
The function is not used anywhere in the codebase and has no associated tests, making it safe to remove as part of the  cleanup.
=> FLS-1470 - Remove unused ORM helper function

app/all_questions/read_forms.py, tests/unit/app/all_questions/test_read_forms.py
This function was faulty. If for example you had a section name 'Section1', it would iterate over all of the characters, see the '1' at the end, and then lop the first character from the start of the string (the 'S'), giving 'ection1'. Not ideal!
The consequences of this function being broken? It was only used in 'view questions' HTML pages, and from inspecting the data in production, we can see that we've fortunately not had any section names that have included digits or full stops after the initial prefix, so this will have had no effect on users.
=> Bugfix - strip leading numbers
